public enum ServerReponseApi
{
    GET_PLAYERS_INFO,
    PLAYER_REGISTRATION,
    START_GAME,
    GAME_STARTED,
    ROLL_DICE,
    AVOID_SWITCH_PLAYER,
    SWITCH_PLAYER,
    PLAYER_MOVED,
    PLAYER_FINISHED_MOVING,
    EXIT_ROOM,
    ONLINE_PLAYERS,
    PROFILE_PIC,
    YOU_WIN,
    ON_PLAYER_WIN
}

public enum ServerRequestApi 
{
    PLAYER_REGISTRATION,
    ON_GAME_STARTED,
    MATCH_MAKING,
    EXIT_ROOM,
    ONLINE_PLAYERS,
    ON_PLAYER_WIN,
    PLAYER_FINISHED_MOVING,
    AVOID_SWITCHING_PLAYER,
    SWITCH_PLAYER,
    PROFILE_PIC,
    MOVE_PLAYER,
    ROLL_DICE,
    ON_QUIT
}
